/*
	This file was generated by ChronCompiler (Bootstrapped)
*/

#include "c_backend/include.h"

typedef ChronObject (*CreateMemoryContextSig)();
ChronObject CreateMemoryContext();
typedef ChronObject (*GetMemoryContextSig)();
ChronObject GetMemoryContext();
typedef ChronVoid (*SetMemoryContextSig)(ChronObject obj);
ChronVoid SetMemoryContext(ChronObject obj);
typedef ChronVoid (*MemoryContext_ReleaseAllSig)();
ChronVoid MemoryContext_ReleaseAll();
typedef ChronVoid (*MemoryContext_ReleaseSig)(ChronObject object);
ChronVoid MemoryContext_Release(ChronObject object);
typedef ChronVoid (*ReleaseMemoryContextSig)(ChronObject object);
ChronVoid ReleaseMemoryContext(ChronObject object);
typedef ChronObject (*ToStringSig)(ChronObject obj);
ChronObject ToString(ChronObject obj);
typedef ChronObject (*TypeOfSig)(ChronObject obj);
ChronObject TypeOf(ChronObject obj);
typedef ChronVoid (*ThrowSig)(ChronObject message);
ChronVoid Throw(ChronObject message);
typedef ChronObject (*CloneSig)(ChronObject object);
ChronObject Clone(ChronObject object);
typedef int (*c_intSig)(ChronObject o);
int c_int(ChronObject o);
typedef const char* (*c_stringSig)(ChronObject o);
const char* c_string(ChronObject o);
typedef bool (*c_boolSig)(ChronObject o);
bool c_bool(ChronObject o);
typedef void* (*c_pointerSig)(ChronObject o);
void* c_pointer(ChronObject o);
typedef ChronObject (*DynIntegerSig)(int i);
ChronObject DynInteger(int i);
typedef ChronObject (*DynStringSig)(const char* s);
ChronObject DynString(const char* s);
typedef ChronObject (*DynBooleanSig)(bool b);
ChronObject DynBoolean(bool b);
typedef ChronObject (*DynPointerSig)(void* ptr);
ChronObject DynPointer(void* ptr);
typedef int (*printfSig)(const char* format, ...);
int printf(const char* format, ...);
typedef ChronVoid (*PrintSig)(ChronObject message);
ChronVoid _F_Print(ChronObject message);
typedef ChronVoid (*PrintLnSig)(ChronObject message);
ChronVoid _F_PrintLn(ChronObject message);
typedef ChronObject (*TableSizeOfSig)(ChronObject table);
ChronObject TableSizeOf(ChronObject table);
typedef ChronObject (*TableIterSig)(ChronObject table);
ChronObject TableIter(ChronObject table);
typedef ChronVoid (*TableInsertSig)(ChronObject table,ChronObject value);
ChronVoid TableInsert(ChronObject table,ChronObject value);
typedef ChronObject (*StringIterSig)(ChronObject str);
ChronObject StringIter(ChronObject str);
typedef ChronObject (*StringContainsSig)(ChronObject source,ChronObject target);
ChronObject StringContains(ChronObject source,ChronObject target);
typedef ChronObject (*StringIndexSig)(ChronObject source,ChronObject index);
ChronObject StringIndex(ChronObject source,ChronObject index);
typedef ChronObject (*StringIsAlphaSig)(ChronObject source);
ChronObject StringIsAlpha(ChronObject source);
typedef ChronObject (*StringIsAlphaNumericSig)(ChronObject source);
ChronObject StringIsAlphaNumeric(ChronObject source);
typedef ChronObject (*StringIsNumericSig)(ChronObject source);
ChronObject StringIsNumeric(ChronObject source);
typedef ChronObject (*StringIsWhitespaceSig)(ChronObject source);
ChronObject StringIsWhitespace(ChronObject source);
typedef ChronObject (*StringLengthSig)(ChronObject source);
ChronObject StringLength(ChronObject source);
typedef ChronObject (*StringReplaceSig)(ChronObject source,ChronObject sub,ChronObject replace);
ChronObject StringReplace(ChronObject source,ChronObject sub,ChronObject replace);
typedef ChronVoid (*MainSig)();
ChronVoid main();
ChronObject CreateMemoryContext()
;
ChronObject GetMemoryContext()
;
ChronVoid SetMemoryContext(ChronObject obj)
;
ChronVoid MemoryContext_ReleaseAll()
;
ChronVoid MemoryContext_Release(ChronObject object)
;
ChronVoid ReleaseMemoryContext(ChronObject object)
;
ChronObject ToString(ChronObject obj)
;
ChronObject TypeOf(ChronObject obj)
;
ChronVoid Throw(ChronObject message)
;
ChronObject Clone(ChronObject object)
;
int c_int(ChronObject o)
;
const char* c_string(ChronObject o)
;
bool c_bool(ChronObject o)
;
void* c_pointer(ChronObject o)
;
ChronObject DynInteger(int i)
;
ChronObject DynString(const char* s)
;
ChronObject DynBoolean(bool b)
;
ChronObject DynPointer(void* ptr)
;
int printf(const char* format, ...)
;
ChronVoid _F_Print(ChronObject message)
{
void* _TEMP_RELEASE_0 = DynString("%s");
void* _TEMP_RELEASE_1 = ToString(message);
printf(c_string(_TEMP_RELEASE_0),c_string(_TEMP_RELEASE_1));
MemoryContext_Release(_TEMP_RELEASE_0);
MemoryContext_Release(_TEMP_RELEASE_1);
}
ChronVoid _F_PrintLn(ChronObject message)
{
void* _TEMP_RELEASE_2 = DynString("%s\n");
void* _TEMP_RELEASE_3 = ToString(message);
printf(c_string(_TEMP_RELEASE_2),c_string(_TEMP_RELEASE_3));
MemoryContext_Release(_TEMP_RELEASE_2);
MemoryContext_Release(_TEMP_RELEASE_3);
}
ChronObject TableSizeOf(ChronObject table)
;
ChronObject TableIter(ChronObject table)
;
ChronVoid TableInsert(ChronObject table,ChronObject value)
;
ChronObject StringIter(ChronObject str)
;
ChronObject StringContains(ChronObject source,ChronObject target)
;
ChronObject StringIndex(ChronObject source,ChronObject index)
;
ChronObject StringIsAlpha(ChronObject source)
;
ChronObject StringIsAlphaNumeric(ChronObject source)
;
ChronObject StringIsNumeric(ChronObject source)
;
ChronObject StringIsWhitespace(ChronObject source)
;
ChronObject StringLength(ChronObject source)
;
ChronObject StringReplace(ChronObject source,ChronObject sub,ChronObject replace)
;
void __InitializeGlobals() {
}
ChronVoid main()
{
__InitializeGlobals();
void* _V_z = DynTable();
void* _TEMP_RELEASE_4 = DynString("Hello");
void* _TEMP_RELEASE_5 = DynString("World");
SetDynamicTable(_V_z,_TEMP_RELEASE_4,_TEMP_RELEASE_5);
MemoryContext_Release(_TEMP_RELEASE_4);
MemoryContext_Release(_TEMP_RELEASE_5);
void* _TEMP_RELEASE_6 = DynInteger(0);
void* _TEMP_RELEASE_7 = DynBoolean(true);
SetDynamicTable(_V_z,_TEMP_RELEASE_6,_TEMP_RELEASE_7);
MemoryContext_Release(_TEMP_RELEASE_6);
MemoryContext_Release(_TEMP_RELEASE_7);
void* _TEMP_RELEASE_8 = DynNil();
void* _TEMP_RELEASE_9 = DynString("Word");
SetDynamicTable(_V_z,_TEMP_RELEASE_8,_TEMP_RELEASE_9);
MemoryContext_Release(_TEMP_RELEASE_8);
MemoryContext_Release(_TEMP_RELEASE_9);
_F_PrintLn(_V_z);
void* _V_y = DynInteger(0);
{
void* _TEMP_RELEASE_10 = DynInteger(0);
void* _TEMP_RELEASE_11 = DynInteger(1);
void* _V_x = DynObjectSub(_TEMP_RELEASE_10,_TEMP_RELEASE_11);
while(1)
{
void* _TEMP_RELEASE_13 = DynInteger(50);
void* _TEMP_WHILE_TMP_12 = DynObjectCompareLesst(_V_x,_TEMP_RELEASE_13);
if(GetBoolean(_TEMP_WHILE_TMP_12) == false) {
MemoryContext_Release(_TEMP_RELEASE_13);
break;
}
MemoryContext_Release(_TEMP_RELEASE_13);
void* _TEMP_RELEASE_14 = DynInteger(1);
_V_x = DynObjectAdd(_V_x,_TEMP_RELEASE_14);
{
_F_PrintLn(_V_x);
}
MemoryContext_Release(_TEMP_RELEASE_14);
}
MemoryContext_Release(_TEMP_RELEASE_10);
MemoryContext_Release(_TEMP_RELEASE_11);
MemoryContext_Release(_V_x);
}
void* _TEMP_RELEASE_15 = DynString("End of program");
_F_PrintLn(_TEMP_RELEASE_15);
MemoryContext_Release(_TEMP_RELEASE_15);
MemoryContext_Release(_V_z);
MemoryContext_Release(_V_y);
}
