/*

	This is a ChronScript module generated by ChronIR(0.1)
	->	Module Name: MyProgram
	->	Build Mode: Debug

*/
#include "include.h"
#define CHRON_DEBUG 1
#define CHRON_MODULE_NAME "MyProgram"
ChronGarbageCollectedObject ReadLine();
ChronVoid Throw(ChronGarbageCollectedObject message);
ChronVoid GC_ReleaseAll();
ChronVoid _I_printf(ChronGarbageCollectedObject p0)
{
	DynObject *o0 = p0->Object;
	const char *r0 = o0->str;
	printf(r0);
}
ChronVoid _I_printf1(ChronGarbageCollectedObject p0, ChronGarbageCollectedObject p1)
{
	DynObject *o0 = p0->Object;
	DynObject *o1 = p1->Object;
	const char *r0 = o0->str;
	const char *r1 = o1->str;
	printf(r0, r1);
}
ChronVoid _F_Print(ChronGarbageCollectedObject message)
{
	PrintRaw(message);
}
ChronVoid _F_PrintLn(ChronGarbageCollectedObject message)
{
	_F_Print(message);
	printf("\n");
}
ChronGarbageCollectedObject _F_GetSomeValue()
{
	return DynString("Hello, world");
}
ChronVoid main()
{
	ChronGarbageCollectedObject _V_SomeVariable = DynString("Hello, world");
	_V_SomeVariable = DynInteger(100);
	_V_SomeVariable = _F_GetSomeValue();
	_I_printf(DynString("Test\n"));
	_I_printf1(DynString("%s\n"), DynString("Hello, world"));
	GC_ReleaseAll();
}
